import json

ALLOWED_GENRES = {
    "Action","Adventure","Animation","Biography","Comedy","Crime","Drama",
    "Family","Fantasy","History","Horror","Music","Mystery","Romance",
    "Sci-Fi","Sport","Thriller","War","Western"
}

# (title, year, genres, director, rating, runtime_minutes, description)
MOVIES = [
    ("Inception", 2010, ("Sci-Fi","Thriller"), "Christopher Nolan", 8.8, 148, "A skilled thief who steals secrets from deep within the subconscious is offered a shot at redemption if he can plant an idea instead of stealing one."),
    ("The Shawshank Redemption", 1994, ("Drama",), "Frank Darabont", 9.3, 142, "Two imprisoned men bond over the years, finding solace and eventual redemption through acts of common decency."),
    ("The Dark Knight", 2008, ("Action","Crime","Drama"), "Christopher Nolan", 9.0, 152, "When a criminal mastermind known as the Joker wreaks havoc on Gotham, a vigilante must confront one of the greatest psychological tests of his ability to fight injustice."),
    ("Pulp Fiction", 1994, ("Crime","Drama"), "Quentin Tarantino", 8.9, 154, "The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine across four tales of violence and redemption."),
    ("Forrest Gump", 1994, ("Drama","Romance"), "Robert Zemeckis", 8.8, 142, "A slow-witted but kind-hearted man from Alabama witnesses and unwittingly influences several defining historical events of the 20th century."),
    ("The Matrix", 1999, ("Sci-Fi","Action"), "Lana Wachowski, Lilly Wachowski", 8.7, 136, "A computer programmer discovers reality as he knows it is a simulation, and joins a rebellion to break free from it."),
    ("Interstellar", 2014, ("Sci-Fi","Drama","Adventure"), "Christopher Nolan", 8.6, 169, "A team of explorers travel through a wormhole in search of a new home for humanity as Earth becomes uninhabitable."),
    ("Parasite", 2019, ("Drama","Thriller"), "Bong Joon-ho", 8.5, 132, "A poor family schemes to become employed by a wealthy household, setting off a chain of consequences no one could have predicted."),
    ("Spirited Away", 2001, ("Animation","Fantasy","Adventure"), "Hayao Miyazaki", 8.6, 125, "A young girl wanders into a magical world of spirits and must find the courage to save her parents and herself."),
    ("The Grand Budapest Hotel", 2014, ("Comedy","Drama"), "Wes Anderson", 8.1, 99, "A legendary hotel concierge and his loyal lobby boy become entangled in a theft and murder investigation involving a family fortune."),
    ("Get Out", 2017, ("Horror","Mystery","Thriller"), "Jordan Peele", 7.7, 104, "A young man uncovers a disturbing secret when he visits his girlfriend's seemingly friendly family estate."),
    ("La La Land", 2016, ("Romance","Music","Drama"), "Damien Chazelle", 8.0, 128, "An aspiring actress and a dedicated jazz musician pursue their dreams, and each other, across the seasons in Los Angeles."),
    ("Mad Max: Fury Road", 2015, ("Action","Adventure","Sci-Fi"), "George Miller", 8.1, 120, "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of escaped prisoners."),
    ("The Fellowship of the Ring", 2001, ("Fantasy","Adventure"), "Peter Jackson", 8.8, 178, "A hobbit and eight companions set out on a perilous journey to destroy a powerful ring before it falls into the wrong hands."),
    ("Toy Story", 1995, ("Animation","Comedy","Family"), "John Lasseter", 8.3, 81, "A cowboy doll's world is turned upside down when a spaceman action figure becomes his owner's new favorite toy."),
    ("Eternal Sunshine of the Spotless Mind", 2004, ("Romance","Sci-Fi","Drama"), "Michel Gondry", 8.3, 108, "A couple undergoes a procedure to erase each other from their memories after their relationship turns sour, with unexpected consequences."),
    ("Whiplash", 2014, ("Drama","Music"), "Damien Chazelle", 8.5, 106, "A promising young drummer enrolls at a cutthroat music conservatory, where a ruthless instructor pushes him to his breaking point."),
    ("The Social Network", 2010, ("Drama","Biography"), "David Fincher", 7.7, 120, "The story of the founding of a revolutionary social media site, and the legal battles that followed among its creators."),
    ("Knives Out", 2019, ("Comedy","Mystery","Thriller"), "Rian Johnson", 7.9, 130, "A detective investigates the death of a wealthy crime novelist during a gathering of his wonderfully dysfunctional family."),
    ("Spider-Man: Into the Spider-Verse", 2018, ("Animation","Action","Adventure"), "Bob Persichetti, Peter Ramsey, Rodney Rothman", 8.4, 117, "A teenager from Brooklyn becomes one of several Spider-People tasked with stopping a threat that spans across parallel universes."),
    ("Coco", 2017, ("Animation","Family","Fantasy"), "Lee Unkrich", 8.4, 105, "A boy is transported to the Land of the Dead, where he uncovers the truth about his family's mysterious history."),
    ("Gladiator", 2000, ("Action","Adventure","Drama"), "Ridley Scott", 8.5, 155, "A betrayed Roman general sets out to seek revenge against the corrupt emperor who murdered his family and stole his throne."),
    ("Amelie", 2001, ("Comedy","Romance"), "Jean-Pierre Jeunet", 8.3, 122, "A shy waitress in Paris secretly sets out to improve the lives of those around her, while struggling to find the courage to pursue her own happiness."),
    ("Django Unchained", 2012, ("Drama","Western"), "Quentin Tarantino", 8.4, 165, "A freed slave partners with a bounty hunter to rescue his wife from a ruthless plantation owner."),
    ("The Prestige", 2006, ("Drama","Mystery","Sci-Fi"), "Christopher Nolan", 8.5, 130, "Two rival stage magicians engage in an escalating battle to create the ultimate illusion, with devastating consequences for both."),
    ("Howl's Moving Castle", 2004, ("Animation","Fantasy","Romance"), "Hayao Miyazaki", 8.2, 119, "A young woman cursed with sudden old age seeks refuge in the moving castle of an eccentric and powerful wizard."),
    ("A Quiet Place", 2018, ("Horror","Sci-Fi","Thriller"), "John Krasinski", 7.5, 90, "A family must live in near-total silence while hiding from creatures that hunt anything that makes a sound."),
    ("The Truman Show", 1998, ("Comedy","Drama","Sci-Fi"), "Peter Weir", 8.2, 103, "An insurance salesman slowly discovers that his entire life is a constructed television show broadcast to the world."),
    ("Blade Runner 2049", 2017, ("Sci-Fi","Drama","Mystery"), "Denis Villeneuve", 8.0, 164, "A young blade runner unearths a long-buried secret that leads him to track down a former blade runner missing for thirty years."),
    ("Little Miss Sunshine", 2006, ("Comedy","Drama"), "Jonathan Dayton, Valerie Faris", 7.8, 101, "A wonderfully dysfunctional family road-trips across the country so their young daughter can compete in a beauty pageant."),

    ("Die Hard", 1988, ("Action","Thriller"), "John McTiernan", 8.2, 132, "An NYPD officer must save his wife and other hostages from terrorists during a Christmas party at a Los Angeles skyscraper."),
    ("Raiders of the Lost Ark", 1981, ("Action","Adventure"), "Steven Spielberg", 8.4, 115, "An archaeologist races Nazi forces to find the legendary Ark of the Covenant before it falls into the wrong hands."),
    ("Terminator 2: Judgment Day", 1991, ("Action","Sci-Fi"), "James Cameron", 8.6, 137, "A cyborg is sent back in time to protect a young boy destined to lead humanity's resistance against machines."),
    ("Aliens", 1986, ("Action","Sci-Fi","Horror"), "James Cameron", 8.4, 137, "A warrant officer returns to the planet where her crew encountered deadly alien creatures, this time with a team of marines."),
    ("Jurassic Park", 1993, ("Action","Adventure","Sci-Fi"), "Steven Spielberg", 8.2, 127, "A theme park of cloned dinosaurs descends into chaos when the security systems fail."),
    ("The Avengers", 2012, ("Action","Adventure","Sci-Fi"), "Joss Whedon", 8.0, 143, "Earth's mightiest heroes must assemble to stop a mischievous god and his alien army from enslaving humanity."),
    ("John Wick", 2014, ("Action","Crime","Thriller"), "Chad Stahelski", 7.4, 101, "A retired hitman comes out of retirement to track down the gangsters who took everything from him."),
    ("Casino Royale", 2006, ("Action","Adventure","Thriller"), "Martin Campbell", 8.0, 144, "A newly minted secret agent takes on a financier of terrorists in a high-stakes poker game."),
    ("The Bourne Identity", 2002, ("Action","Mystery","Thriller"), "Doug Liman", 7.9, 119, "A man is found floating in the ocean with no memory of who he is, and must piece together his violent past."),
    ("Top Gun: Maverick", 2022, ("Action","Drama"), "Joseph Kosinski", 8.3, 130, "A veteran fighter pilot is called back to train a new group of graduates for a dangerous mission."),
    ("Speed", 1994, ("Action","Thriller"), "Jan de Bont", 7.3, 116, "A young police officer must keep a bus moving above fifty miles per hour or a bomb aboard will detonate."),
    ("Indiana Jones and the Last Crusade", 1989, ("Action","Adventure"), "Steven Spielberg", 8.2, 127, "An archaeologist teams up with his estranged father to find the Holy Grail before the Nazis do."),
    ("Kill Bill: Vol. 1", 2003, ("Action","Crime","Thriller"), "Quentin Tarantino", 8.2, 111, "A former assassin seeks revenge on the team of killers who betrayed her on her wedding day."),
    ("The Bourne Ultimatum", 2007, ("Action","Mystery","Thriller"), "Paul Greengrass", 8.0, 115, "A trained assassin continues to hunt down the truth about the black-ops program that created him."),
    ("Skyfall", 2012, ("Action","Adventure","Thriller"), "Sam Mendes", 7.8, 143, "A secret agent investigates an attack on his agency that leads him to a former operative with a personal vendetta."),
    ("Edge of Tomorrow", 2014, ("Action","Sci-Fi"), "Doug Liman", 7.9, 113, "A soldier fighting aliens gets caught in a time loop, reliving the same brutal day of combat over and over."),
    ("Logan", 2017, ("Action","Drama","Sci-Fi"), "James Mangold", 8.1, 137, "An aging mutant hero cares for an ailing mentor while protecting a young girl with dangerous powers from dark forces."),
    ("The Raid", 2011, ("Action","Crime","Thriller"), "Gareth Evans", 7.6, 101, "A SWAT team becomes trapped in a tenement building run by a ruthless crime lord."),
    ("Mission: Impossible - Fallout", 2018, ("Action","Adventure","Thriller"), "Christopher McQuarrie", 7.7, 147, "An agent and his team race against time after a mission gone wrong threatens to unleash a global catastrophe."),
    ("Black Panther", 2018, ("Action","Adventure","Sci-Fi"), "Ryan Coogler", 7.3, 134, "The new king of a hidden, technologically advanced African nation must defend his throne from a vengeful challenger."),

    ("2001: A Space Odyssey", 1968, ("Sci-Fi","Adventure"), "Stanley Kubrick", 8.3, 149, "A voyage to Jupiter with a sentient computer reveals mysteries about human evolution and existence."),
    ("Blade Runner", 1982, ("Sci-Fi","Drama","Thriller"), "Ridley Scott", 8.1, 117, "A weary detective hunts down bioengineered humans hiding on Earth in a neon-drenched future."),
    ("Alien", 1979, ("Sci-Fi","Horror"), "Ridley Scott", 8.5, 117, "The crew of a commercial spacecraft encounters a deadly extraterrestrial organism after investigating a distress signal."),
    ("Arrival", 2016, ("Sci-Fi","Drama","Mystery"), "Denis Villeneuve", 7.9, 116, "A linguist is recruited to communicate with mysterious alien visitors before global tensions escalate into war."),
    ("Ex Machina", 2014, ("Sci-Fi","Drama","Thriller"), "Alex Garland", 7.7, 108, "A programmer is invited to administer a test to determine whether a stunning humanoid AI is truly conscious."),
    ("Dune", 2021, ("Sci-Fi","Adventure","Drama"), "Denis Villeneuve", 8.0, 155, "A young heir must navigate treachery and prophecy on a dangerous desert planet that holds the universe's most valuable resource."),
    ("Her", 2013, ("Sci-Fi","Drama","Romance"), "Spike Jonze", 8.0, 126, "A lonely writer develops an unlikely relationship with an intelligent operating system designed to meet his every need."),
    ("District 9", 2009, ("Sci-Fi","Action","Thriller"), "Neill Blomkamp", 7.9, 112, "An extraterrestrial race confined to a slum on Earth becomes the center of a bureaucrat's moral awakening."),
    ("Children of Men", 2006, ("Sci-Fi","Drama","Thriller"), "Alfonso Cuaron", 7.9, 109, "In a future where humanity has become infertile, a former activist must protect the world's only pregnant woman."),
    ("Gattaca", 1997, ("Sci-Fi","Drama","Thriller"), "Andrew Niccol", 7.8, 106, "In a genetically engineered future, a man with natural-born flaws assumes another's identity to pursue his dream of space travel."),
    ("The Fifth Element", 1997, ("Sci-Fi","Action","Adventure"), "Luc Besson", 7.6, 126, "A cab driver becomes humanity's unlikely last hope when he's drawn into a battle to stop an ancient evil."),
    ("Minority Report", 2002, ("Sci-Fi","Action","Mystery"), "Steven Spielberg", 7.6, 145, "A police chief who hunts down criminals before they commit their crimes becomes the prime suspect in a future murder."),
    ("WALL-E", 2008, ("Animation","Sci-Fi","Family"), "Andrew Stanton", 8.4, 98, "A lonely trash-compacting robot on a deserted Earth falls for a sleek probe sent to search for signs of life."),
    ("Looper", 2012, ("Sci-Fi","Action","Thriller"), "Rian Johnson", 7.4, 118, "A hitman who kills targets sent back in time from the future is forced to confront his own future self."),
    ("Everything Everywhere All at Once", 2022, ("Sci-Fi","Comedy","Drama"), "Daniel Kwan, Daniel Scheinert", 7.8, 140, "An overwhelmed laundromat owner discovers she must connect with parallel universe versions of herself to save existence."),

    ("The Lion King", 1994, ("Animation","Adventure","Drama"), "Roger Allers, Rob Minkoff", 8.5, 88, "A young lion prince flees his kingdom after his father's murder, only to learn the true meaning of responsibility and courage."),
    ("Up", 2009, ("Animation","Adventure","Comedy"), "Pete Docter", 8.3, 96, "An elderly widower ties thousands of balloons to his house and sets off on the adventure he always promised his late wife."),
    ("Finding Nemo", 2003, ("Animation","Adventure","Comedy"), "Andrew Stanton", 8.2, 100, "An anxious clownfish sets off across the ocean to rescue his son, who was captured by a diver."),
    ("Inside Out", 2015, ("Animation","Comedy","Drama"), "Pete Docter", 8.1, 95, "The five emotions inside a young girl's mind struggle to guide her through a difficult family move."),
    ("Ratatouille", 2007, ("Animation","Comedy","Family"), "Brad Bird", 8.1, 111, "A rat with dreams of becoming a chef forms an unlikely partnership with a young kitchen worker in Paris."),
    ("How to Train Your Dragon", 2010, ("Animation","Action","Adventure"), "Dean DeBlois, Chris Sanders", 8.1, 98, "A young Viking befriends the dragon he was raised to hate, challenging centuries of conflict between their peoples."),
    ("Shrek", 2001, ("Animation","Adventure","Comedy"), "Andrew Adamson, Vicky Jenson", 7.9, 90, "A grumpy ogre reluctantly sets out to rescue a princess in order to reclaim his swamp from banished fairy tale creatures."),
    ("Zootopia", 2016, ("Animation","Adventure","Comedy"), "Byron Howard, Rich Moore", 8.0, 108, "A rookie rabbit officer and a con-artist fox uncover a conspiracy in a city where predators and prey live side by side."),
    ("The Incredibles", 2004, ("Animation","Action","Adventure"), "Brad Bird", 8.0, 115, "A family of retired superheroes is forced back into action to save the world and rediscover what makes them a family."),
    ("My Neighbor Totoro", 1988, ("Animation","Family","Fantasy"), "Hayao Miyazaki", 8.1, 86, "Two young sisters befriend gentle forest spirits after moving to the countryside to be near their ailing mother."),
    ("Princess Mononoke", 1997, ("Animation","Adventure","Fantasy"), "Hayao Miyazaki", 8.4, 134, "A prince becomes entangled in a war between forest gods and a mining colony that threatens the natural world."),
    ("Akira", 1988, ("Animation","Action","Sci-Fi"), "Katsuhiro Otomo", 8.0, 124, "A biker gang leader's friend develops terrifying psychic powers after a government experiment goes wrong in a dystopian Tokyo."),
    ("Persepolis", 2007, ("Animation","Biography","Drama"), "Vincent Paronnaud, Marjane Satrapi", 8.0, 96, "A young girl comes of age during the Iranian Revolution, navigating identity and exile in a changing world."),
    ("Klaus", 2019, ("Animation","Adventure","Comedy"), "Sergio Pablos", 8.2, 96, "A spoiled postman is banished to a frozen town, where an unlikely friendship with a reclusive toymaker sparks a new legend."),
    ("The Iron Giant", 1999, ("Animation","Action","Adventure"), "Brad Bird", 8.1, 86, "A boy befriends a giant robot from outer space and works to protect him from a paranoid government agent."),

    ("Groundhog Day", 1993, ("Comedy","Fantasy","Romance"), "Harold Ramis", 8.0, 101, "A cynical weatherman is forced to relive the same day over and over until he learns to become a better person."),
    ("Superbad", 2007, ("Comedy",), "Greg Mottola", 7.6, 113, "Two inseparable high school friends embark on a chaotic quest to buy alcohol for a party before they head off to separate colleges."),
    ("Bridesmaids", 2011, ("Comedy","Romance"), "Paul Feig", 6.8, 125, "A maid of honor's life unravels as she competes with a new bridesmaid for her best friend's affection ahead of the wedding."),
    ("The Hangover", 2009, ("Comedy",), "Todd Phillips", 7.7, 100, "Three friends must retrace their blackout night in Las Vegas to find the missing groom before the wedding."),
    ("Anchorman: The Legend of Ron Burgundy", 2004, ("Comedy",), "Adam McKay", 7.2, 94, "A vain 1970s news anchor's world is turned upside down when a talented woman joins his previously all-male team."),
    ("Ferris Bueller's Day Off", 1986, ("Comedy",), "John Hughes", 7.8, 103, "A charismatic high schooler skips class for a wild day in the city while his suspicious principal tries to catch him."),
    ("Napoleon Dynamite", 2004, ("Comedy",), "Jared Hess", 6.9, 82, "An awkward small-town teenager navigates high school, family chaos, and his best friend's run for class president."),
    ("Booksmart", 2019, ("Comedy",), "Olivia Wilde", 7.1, 105, "Two academically driven best friends try to cram four years of fun into one wild night before graduation."),
    ("The Big Lebowski", 1998, ("Comedy","Crime"), "Joel Coen, Ethan Coen", 8.1, 117, "A laid-back slacker is mistaken for a millionaire of the same name and dragged into a bizarre kidnapping scheme."),
    ("Dumb and Dumber", 1994, ("Comedy",), "Peter Farrelly, Bobby Farrelly", 7.3, 107, "Two well-meaning but dim-witted friends drive cross-country to return a briefcase to its rightful owner."),
    ("Legally Blonde", 2001, ("Comedy","Romance"), "Robert Luketic", 6.4, 96, "A sorority queen enrolls at Harvard Law School to win back her ex, and discovers she's smarter than anyone gave her credit for."),
    ("Mean Girls", 2004, ("Comedy",), "Mark Waters", 7.1, 97, "A homeschooled teenager learns the brutal social rules of high school after infiltrating a clique of ruthless popular girls."),
    ("Borat", 2006, ("Comedy",), "Larry Charles", 7.3, 84, "A Kazakh television journalist travels across America, capturing unscripted and increasingly outrageous encounters along the way."),
    ("Zombieland", 2009, ("Comedy","Horror"), "Ruben Fleischer", 7.6, 88, "A group of mismatched survivors bond and battle their way across a zombie-ravaged country in search of safety."),
    ("What We Do in the Shadows", 2014, ("Comedy","Horror"), "Jemaine Clement, Taika Waititi", 7.7, 86, "A documentary crew follows a group of ancient vampire roommates struggling with the mundane realities of modern life."),

    ("Schindler's List", 1993, ("Drama","Biography","History"), "Steven Spielberg", 9.0, 195, "A German businessman gradually becomes determined to save his Jewish employees from the horrors of the Holocaust."),
    ("Fight Club", 1999, ("Drama",), "David Fincher", 8.8, 139, "An insomniac office worker and a soap salesman form an underground fight club that spirals into something much larger and more dangerous."),
    ("Goodfellas", 1990, ("Drama","Crime","Biography"), "Martin Scorsese", 8.7, 145, "A young man's rise through the ranks of the mob is chronicled across three decades of crime, loyalty, and betrayal."),
    ("The Green Mile", 1999, ("Drama","Fantasy","Crime"), "Frank Darabont", 8.6, 189, "A death row prison guard witnesses extraordinary events after a condemned man with a miraculous gift arrives on the block."),
    ("American History X", 1998, ("Drama","Crime"), "Tony Kaye", 8.5, 119, "A reformed neo-Nazi tries to prevent his younger brother from going down the same violent path he once took."),
    ("The Departed", 2006, ("Drama","Crime","Thriller"), "Martin Scorsese", 8.5, 151, "An undercover cop and a mole in the police force try to identify each other while infiltrating the Irish mob."),
    ("There Will Be Blood", 2007, ("Drama",), "Paul Thomas Anderson", 8.2, 158, "A ruthless silver miner turned oil tycoon builds an empire in the early 20th century California oil boom."),
    ("No Country for Old Men", 2007, ("Drama","Crime","Thriller"), "Joel Coen, Ethan Coen", 8.2, 122, "A hunter who stumbles upon a drug deal gone wrong is pursued by a relentless killer across the Texas desert."),
    ("12 Years a Slave", 2013, ("Drama","Biography","History"), "Steve McQueen", 8.1, 134, "A free Black man is kidnapped and sold into slavery, enduring years of brutality while fighting to reclaim his freedom."),
    ("Moonlight", 2016, ("Drama",), "Barry Jenkins", 7.4, 111, "A young Black man's coming-of-age is traced across three chapters as he grapples with identity, sexuality, and belonging."),
    ("Manchester by the Sea", 2016, ("Drama",), "Kenneth Lonergan", 7.8, 137, "A withdrawn handyman is forced to confront his past when he becomes the guardian of his teenage nephew after a family tragedy."),
    ("A Beautiful Mind", 2001, ("Drama","Biography"), "Ron Howard", 8.2, 135, "A brilliant mathematician's groundbreaking career is upended by the onset of schizophrenia."),
    ("Good Will Hunting", 1997, ("Drama",), "Gus Van Sant", 8.3, 126, "A janitor with a genius-level intellect must confront his troubled past with the help of a therapist and a mentor."),
    ("The Pianist", 2002, ("Drama","Biography","War"), "Roman Polanski", 8.5, 150, "A Polish-Jewish pianist struggles to survive the destruction of Warsaw during the Second World War."),
    ("Requiem for a Dream", 2000, ("Drama",), "Darren Aronofsky", 8.3, 102, "Four people's lives spiral into addiction as their individual pursuits of a better life turn into devastating dependency."),
    ("American Beauty", 1999, ("Drama",), "Sam Mendes", 8.3, 122, "A suburban father's midlife crisis unravels the carefully maintained facade of his family's picture-perfect life."),
    ("The Curious Case of Benjamin Button", 2008, ("Drama","Fantasy","Romance"), "David Fincher", 7.8, 166, "A man born with the appearance of old age ages in reverse, living his life backward through the twentieth century."),
    ("Marriage Story", 2019, ("Drama",), "Noah Baumbach", 7.9, 137, "A stage director and his actress wife struggle through a painful and revealing coast-to-coast divorce."),
    ("The Wolf of Wall Street", 2013, ("Drama","Biography","Comedy"), "Martin Scorsese", 8.2, 180, "A stockbroker's rapid rise to wealth through fraud and excess leads to an equally spectacular fall."),
    ("Room", 2015, ("Drama",), "Lenny Abrahamson", 8.1, 118, "A mother and her five-year-old son held captive in a small room must adjust to a world neither of them fully understands after their escape."),

    ("Se7en", 1995, ("Crime","Drama","Thriller"), "David Fincher", 8.6, 127, "Two detectives hunt a serial killer who uses the seven deadly sins as his method and motive."),
    ("Zodiac", 2007, ("Crime","Drama","Mystery"), "David Fincher", 7.7, 157, "A cartoonist becomes obsessed with identifying the elusive serial killer terrorizing the San Francisco Bay Area."),
    ("The Silence of the Lambs", 1991, ("Crime","Drama","Thriller"), "Jonathan Demme", 8.6, 118, "A young FBI trainee seeks the counsel of an imprisoned cannibalistic killer to catch another serial murderer."),
    ("Heat", 1995, ("Crime","Drama","Thriller"), "Michael Mann", 8.3, 170, "A master thief and the relentless detective hunting him find their lives inextricably crossing paths."),
    ("The Usual Suspects", 1995, ("Crime","Drama","Mystery"), "Bryan Singer", 8.5, 106, "A sole survivor of a boat explosion tells a convoluted story to investigators about the mysterious criminal mastermind behind it."),
    ("Memento", 2000, ("Mystery","Thriller"), "Christopher Nolan", 8.4, 113, "A man with short-term memory loss uses notes and tattoos to hunt down his wife's killer."),
    ("Prisoners", 2013, ("Crime","Drama","Mystery"), "Denis Villeneuve", 8.1, 153, "A father takes matters into his own hands when police fail to find his daughter and her friend after their abduction."),
    ("Gone Girl", 2014, ("Drama","Mystery","Thriller"), "David Fincher", 8.1, 149, "A man becomes the prime suspect in his wife's disappearance as the case reveals disturbing truths about their marriage."),
    ("Nightcrawler", 2014, ("Crime","Drama","Thriller"), "Dan Gilroy", 7.8, 117, "An unscrupulous freelance cameraman will do anything to capture the most graphic crime footage for the morning news."),
    ("Uncut Gems", 2019, ("Crime","Drama","Thriller"), "Josh Safdie, Benny Safdie", 7.4, 135, "A charismatic jeweler and gambling addict makes a series of increasingly high-stakes bets to score a windfall."),
    ("Baby Driver", 2017, ("Action","Crime","Music"), "Edgar Wright", 7.6, 113, "A talented getaway driver who relies on music to steady his focus tries to leave crime behind for the woman he loves."),
    ("American Psycho", 2000, ("Crime","Drama","Horror"), "Mary Harron", 7.6, 102, "A wealthy 1980s investment banker hides a horrifying secret life as a serial killer behind his polished exterior."),
    ("Reservoir Dogs", 1992, ("Crime","Drama","Thriller"), "Quentin Tarantino", 8.3, 99, "A botched jewelry heist leaves a gang of criminals questioning which one of them is a police informant."),

    ("The Shining", 1980, ("Horror","Drama"), "Stanley Kubrick", 8.4, 146, "A writer's descent into madness at an isolated, haunted hotel puts his wife and psychic son in grave danger."),
    ("Hereditary", 2018, ("Horror","Drama","Mystery"), "Ari Aster", 7.3, 127, "A family unravels dark secrets and inherited trauma following the death of their secretive grandmother."),
    ("The Exorcist", 1973, ("Horror",), "William Friedkin", 8.1, 122, "A mother seeks the help of two priests when her young daughter is possessed by a mysterious and terrifying entity."),
    ("It Follows", 2014, ("Horror","Mystery"), "David Robert Mitchell", 6.8, 100, "A young woman is stalked by a shapeshifting entity after a sexual encounter passes a deadly curse onto her."),
    ("The Conjuring", 2013, ("Horror","Mystery","Thriller"), "James Wan", 7.5, 112, "Paranormal investigators help a family terrorized by a dark presence in their farmhouse."),
    ("Midsommar", 2019, ("Horror","Drama","Mystery"), "Ari Aster", 7.1, 148, "A grieving woman's trip to a Swedish festival with her boyfriend descends into a surreal and disturbing nightmare."),
    ("The Babadook", 2014, ("Horror","Drama","Mystery"), "Jennifer Kent", 6.8, 94, "A widowed mother and her troubled son are tormented by a sinister presence conjured from the pages of a mysterious book."),
    ("28 Days Later", 2002, ("Horror","Sci-Fi","Thriller"), "Danny Boyle", 7.6, 113, "A man wakes from a coma to find Britain devastated by a rage-inducing virus that has turned most of the population into the infected."),
    ("Halloween", 1978, ("Horror","Thriller"), "John Carpenter", 7.7, 91, "A masked killer stalks a small Illinois town on Halloween night, years after murdering his sister as a child."),
    ("Psycho", 1960, ("Horror","Mystery","Thriller"), "Alfred Hitchcock", 8.5, 109, "A secretary on the run checks into a remote motel run by a disturbed man and his domineering mother."),
    ("The Witch", 2015, ("Horror","Mystery"), "Robert Eggers", 6.9, 92, "A Puritan family's faith and sanity unravel after their infant disappears near the ominous woods bordering their farm."),
    ("Scream", 1996, ("Horror","Mystery","Comedy"), "Wes Craven", 7.4, 111, "A masked killer begins stalking a small town's teenagers, all of whom seem to know a little too much about horror movies."),
    ("A Nightmare on Elm Street", 1984, ("Horror","Fantasy"), "Wes Craven", 7.4, 91, "A group of teenagers are stalked in their dreams by a disfigured killer who can murder them in their sleep."),
    ("Us", 2019, ("Horror","Mystery","Thriller"), "Jordan Peele", 6.8, 116, "A family's beach vacation turns into a nightmare when they're confronted by sinister doubles of themselves."),
    ("Train to Busan", 2016, ("Horror","Action","Thriller"), "Yeon Sang-ho", 7.6, 118, "Passengers on a high-speed train fight to survive as a zombie outbreak spreads uncontrollably across South Korea."),

    ("Titanic", 1997, ("Romance","Drama"), "James Cameron", 7.9, 195, "A penniless artist and a wealthy young woman fall in love aboard the doomed maiden voyage of an unsinkable ship."),
    ("The Notebook", 2004, ("Romance","Drama"), "Nick Cassavetes", 7.8, 123, "An elderly man reads a story to a woman with dementia about two young lovers separated by class and circumstance."),
    ("Pride & Prejudice", 2005, ("Romance","Drama"), "Joe Wright", 7.8, 129, "A spirited young woman navigates love, class, and misunderstanding with a proud and wealthy gentleman in Regency-era England."),
    ("When Harry Met Sally...", 1989, ("Romance","Comedy"), "Rob Reiner", 7.7, 96, "Two friends debate for over a decade whether men and women can ever truly just be friends."),
    ("Before Sunrise", 1995, ("Romance","Drama"), "Richard Linklater", 8.1, 101, "Two strangers meet on a train and spend one unforgettable night walking and talking through the streets of Vienna."),
    ("Silver Linings Playbook", 2012, ("Romance","Comedy","Drama"), "David O. Russell", 7.7, 122, "Two people with unresolved struggles form an unconventional bond while training for a dance competition."),
    ("About Time", 2013, ("Romance","Comedy","Fantasy"), "Richard Curtis", 7.8, 123, "A young man discovers he can travel back in time and uses the gift to try to improve his love life and his family."),
    ("500 Days of Summer", 2009, ("Romance","Comedy","Drama"), "Marc Webb", 7.7, 95, "A hopeless romantic looks back on his relationship with a woman who never quite believed in true love the way he did."),
    ("Notting Hill", 1999, ("Romance","Comedy"), "Roger Michell", 7.2, 124, "A humble London bookshop owner's life is upended when he falls for one of the most famous actresses in the world."),
    ("Crazy Rich Asians", 2018, ("Romance","Comedy","Drama"), "Jon M. Chu", 6.9, 120, "A woman travels to meet her boyfriend's family, only to discover they're one of the wealthiest in Singapore."),

    ("Bohemian Rhapsody", 2018, ("Music","Biography","Drama"), "Bryan Singer", 7.9, 134, "The story of a rock band's meteoric rise, built around the singular voice and vision of their flamboyant frontman."),
    ("A Star Is Born", 2018, ("Music","Romance","Drama"), "Bradley Cooper", 7.6, 136, "A fading musician discovers and falls in love with a struggling singer, launching her to stardom as his own career collapses."),
    ("Once", 2007, ("Music","Drama","Romance"), "John Carney", 7.8, 85, "A busking street musician and a Czech immigrant write and record songs together over the course of one transformative week."),
    ("Sing Street", 2016, ("Music","Comedy","Drama"), "John Carney", 7.9, 106, "A teenager in 1980s Dublin starts a band to impress a girl, discovering his own voice along the way."),
    ("The Greatest Showman", 2017, ("Music","Biography","Drama"), "Michael Gracey", 7.6, 105, "A visionary showman builds a spectacular circus that celebrates the extraordinary and unites an eclectic troupe of outcasts."),
    ("Rocketman", 2019, ("Music","Biography","Drama"), "Dexter Fletcher", 7.3, 121, "A flamboyant musician's turbulent journey from a shy piano prodigy to international superstardom is told through fantastical musical sequences."),

    ("Shutter Island", 2010, ("Mystery","Thriller","Drama"), "Martin Scorsese", 8.2, 138, "A U.S. Marshal investigating a psychiatric facility begins to question his own sanity as disturbing truths emerge."),
    ("Rear Window", 1954, ("Mystery","Thriller"), "Alfred Hitchcock", 8.5, 112, "A wheelchair-bound photographer becomes convinced his neighbor has committed murder after watching him from his apartment window."),
    ("Vertigo", 1958, ("Mystery","Romance","Thriller"), "Alfred Hitchcock", 8.3, 128, "A former detective with a fear of heights becomes dangerously obsessed with a woman he was hired to follow."),
    ("Chinatown", 1974, ("Mystery","Crime","Drama"), "Roman Polanski", 8.1, 130, "A private detective investigating a case of adultery uncovers a conspiracy involving water rights and murder in 1930s Los Angeles."),
    ("The Girl with the Dragon Tattoo", 2011, ("Mystery","Crime","Thriller"), "David Fincher", 7.8, 158, "A disgraced journalist and a troubled hacker investigate a decades-old disappearance for a wealthy Swedish family."),
    ("Enemy", 2013, ("Mystery","Thriller"), "Denis Villeneuve", 6.9, 91, "A history professor is unsettled to discover a man who looks exactly like him working as a background actor."),

    ("The Two Towers", 2002, ("Fantasy","Adventure"), "Peter Jackson", 8.8, 179, "The fellowship is scattered as new alliances form to stand against a rising darkness threatening Middle-earth."),
    ("The Return of the King", 2003, ("Fantasy","Adventure"), "Peter Jackson", 9.0, 201, "The final battle for Middle-earth begins as the fate of the world rests on the shoulders of two small hobbits."),
    ("Harry Potter and the Sorcerer's Stone", 2001, ("Fantasy","Adventure","Family"), "Chris Columbus", 7.6, 152, "An orphaned boy discovers he's a wizard and begins his first year at a magical school of witchcraft and wizardry."),
    ("Harry Potter and the Prisoner of Azkaban", 2004, ("Fantasy","Adventure","Family"), "Alfonso Cuaron", 7.9, 142, "A young wizard learns unsettling truths about his past when a dangerous escaped prisoner is said to be hunting him."),
    ("Pan's Labyrinth", 2006, ("Fantasy","Drama","War"), "Guillermo del Toro", 8.2, 118, "A young girl escapes into a dark fairy-tale world of her own imagining amid the brutal aftermath of the Spanish Civil War."),
    ("Edward Scissorhands", 1990, ("Fantasy","Drama","Romance"), "Tim Burton", 7.9, 105, "A gentle artificial man with scissors for hands is taken in by a suburban family and struggles to find where he belongs."),
    ("The Princess Bride", 1987, ("Fantasy","Adventure","Romance"), "Rob Reiner", 8.0, 98, "A farmhand-turned-pirate must rescue his true love from an arranged marriage to a scheming prince."),
    ("Big Fish", 2003, ("Fantasy","Drama","Adventure"), "Tim Burton", 8.0, 125, "A son tries to separate fact from fantasy in his dying father's tall tales about an extraordinary life."),
    ("Coraline", 2009, ("Fantasy","Animation","Family"), "Henry Selick", 7.7, 100, "A curious girl discovers an idealized parallel world behind a secret door in her new home, one that hides a sinister secret."),
    ("Stardust", 2007, ("Fantasy","Adventure","Romance"), "Matthew Vaughn", 7.6, 127, "A young man ventures into a magical kingdom to retrieve a fallen star and win the heart of the woman he loves."),

    ("Saving Private Ryan", 1998, ("War","Drama"), "Steven Spielberg", 8.6, 169, "A group of soldiers is sent behind enemy lines to bring home a paratrooper whose brothers have all been killed in action."),
    ("Full Metal Jacket", 1987, ("War","Drama"), "Stanley Kubrick", 8.3, 116, "A platoon of Marine recruits endures brutal training before facing the chaos and horror of the Vietnam War."),
    ("Apocalypse Now", 1979, ("War","Drama"), "Francis Ford Coppola", 8.4, 147, "A captain travels deep into the Cambodian jungle to assassinate a renegade colonel who has established himself as a god among a local tribe."),
    ("1917", 2019, ("War","Drama"), "Sam Mendes", 8.2, 119, "Two young soldiers race against time to deliver a message that could save thousands of lives on the front lines of World War I."),
    ("Dunkirk", 2017, ("War","Action","Drama"), "Christopher Nolan", 7.8, 106, "Allied soldiers are surrounded and evacuated from a French beach by a makeshift fleet of civilian and military vessels."),
    ("Hacksaw Ridge", 2016, ("War","Biography","Drama"), "Mel Gibson", 8.1, 139, "A pacifist combat medic saves dozens of lives during one of the bloodiest battles of World War II without ever carrying a weapon."),
    ("Braveheart", 1995, ("War","Biography","Drama"), "Mel Gibson", 8.3, 178, "A Scottish warrior leads an uprising against the tyranny of the English crown after the murder of his wife."),
    ("Letters from Iwo Jima", 2006, ("War","Drama","History"), "Clint Eastwood", 7.9, 141, "Japanese soldiers defending an island fortress face the final days of a doomed campaign during World War II."),
    ("The Imitation Game", 2014, ("Biography","Drama","War"), "Morten Tyldum", 8.0, 114, "A brilliant mathematician leads a team of codebreakers racing to crack Nazi Germany's Enigma cipher."),
    ("Darkest Hour", 2017, ("Biography","Drama","War"), "Joe Wright", 7.4, 125, "A newly appointed prime minister must decide whether to negotiate with an advancing enemy or rally a nation to fight on."),

    ("Steve Jobs", 2015, ("Biography","Drama"), "Danny Boyle", 7.2, 122, "The story of a visionary and volatile tech founder is told across three pivotal product launches that defined his career."),
    ("Rush", 2013, ("Biography","Action","Drama"), "Ron Howard", 8.1, 123, "The fierce rivalry between two Formula One drivers pushes both men to the limits of their talent and daring."),
    ("The Theory of Everything", 2014, ("Biography","Drama","Romance"), "James Marsh", 7.7, 123, "A brilliant physics student's diagnosis with a degenerative disease transforms his life and his groundbreaking work on the universe."),
    ("Catch Me If You Can", 2002, ("Biography","Crime","Drama"), "Steven Spielberg", 8.1, 141, "An FBI agent pursues a brilliant young con artist who has successfully impersonated a doctor, lawyer, and airline pilot."),
    ("Ford v Ferrari", 2019, ("Biography","Action","Drama"), "James Mangold", 8.1, 152, "An American car designer and a fearless driver battle corporate interference to build a race car that can beat Ferrari at Le Mans."),
    ("Lincoln", 2012, ("Biography","Drama","History"), "Steven Spielberg", 7.3, 150, "The president fights to pass the constitutional amendment that would abolish slavery in the final months of the Civil War."),
    ("Milk", 2008, ("Biography","Drama","History"), "Gus Van Sant", 7.5, 128, "A gay rights activist becomes one of the first openly gay elected officials in the United States, inspiring a movement."),

    ("Rocky", 1976, ("Sport","Drama"), "John G. Avildsen", 8.1, 120, "A small-time boxer gets a once-in-a-lifetime shot at the heavyweight title against the reigning champion."),
    ("Moneyball", 2011, ("Sport","Biography","Drama"), "Bennett Miller", 7.6, 133, "A struggling baseball team's general manager builds a competitive roster using an unconventional, data-driven approach."),
    ("The Blind Side", 2009, ("Sport","Biography","Drama"), "John Lee Hancock", 7.6, 129, "A homeless teenager is taken in by a wealthy family who help him become one of the most sought-after football players in the country."),
    ("Miracle", 2004, ("Sport","Drama","History"), "Gavin O'Connor", 7.6, 135, "A college hockey coach molds a group of amateur players into a team capable of defeating the seemingly invincible Soviet squad."),
    ("Creed", 2015, ("Sport","Drama"), "Ryan Coogler", 7.6, 133, "The son of a legendary boxer seeks out his father's greatest rival to help him make his own name in the ring."),
    ("Warrior", 2011, ("Sport","Drama"), "Gavin O'Connor", 8.1, 140, "Two estranged brothers, one a soldier and one a teacher, find themselves on a collision course as competitors in a mixed martial arts tournament."),

    ("The Good, the Bad and the Ugly", 1966, ("Western",), "Sergio Leone", 8.8, 178, "Three gunslingers compete to find a fortune in buried Confederate gold during the chaos of the American Civil War."),
    ("Unforgiven", 1992, ("Western","Drama"), "Clint Eastwood", 8.2, 130, "A retired gunslinger reluctantly takes one last job, forced to confront the violent legacy he's tried to leave behind."),
    ("True Grit", 2010, ("Western","Drama"), "Joel Coen, Ethan Coen", 7.6, 110, "A determined young girl hires a boozy U.S. Marshal to help her track down her father's killer through Indian territory."),
    ("The Revenant", 2015, ("Western","Adventure","Drama"), "Alejandro G. Inarritu", 8.0, 156, "A frontiersman left for dead by his hunting party fights to survive and seek revenge in the unforgiving wilderness."),
    ("Butch Cassidy and the Sundance Kid", 1969, ("Western","Biography","Crime"), "George Roy Hill", 8.0, 110, "Two outlaws flee to South America after a string of train robberies makes them the target of a relentless posse."),

    ("Home Alone", 1990, ("Family","Comedy"), "Chris Columbus", 7.7, 103, "An eight-year-old boy accidentally left behind by his family at Christmas must defend his house from two bumbling burglars."),
    ("E.T. the Extra-Terrestrial", 1982, ("Family","Sci-Fi","Adventure"), "Steven Spielberg", 7.9, 115, "A lonely boy befriends a stranded alien and helps him find a way back home before government agents can find him first."),
    ("The Sandlot", 1993, ("Family","Comedy"), "David Mickey Evans", 7.8, 101, "A group of neighborhood boys spend an unforgettable summer playing baseball and chasing down a legendary fence-guarding dog."),
    ("Paddington 2", 2017, ("Family","Adventure","Comedy"), "Paul King", 7.8, 103, "A polite young bear must clear his name after being wrongly imprisoned for a theft he didn't commit."),
    ("Matilda", 1996, ("Family","Comedy","Fantasy"), "Danny DeVito", 7.3, 98, "A gifted young girl with telekinetic powers uses her abilities to stand up to her neglectful parents and tyrannical headmistress."),
    ("Charlie and the Chocolate Factory", 2005, ("Family","Adventure","Comedy"), "Tim Burton", 6.7, 115, "A poor boy wins a golden ticket to tour the strange and wondrous chocolate factory of an eccentric candy maker."),
    ("Chronicles of Narnia: The Lion, the Witch and the Wardrobe", 2005, ("Family","Adventure","Fantasy"), "Andrew Adamson", 6.9, 143, "Four siblings discover a magical land trapped in eternal winter and join a quest to free it from an evil queen."),
    ("Willy Wonka & the Chocolate Factory", 1971, ("Family","Fantasy","Comedy"), "Mel Stuart", 7.8, 100, "A poor boy's golden ticket wins him a tour through the strange and wondrous chocolate factory of a reclusive candy maker."),
    ("Back to the Future", 1985, ("Adventure","Comedy","Sci-Fi"), "Robert Zemeckis", 8.5, 116, "A teenager is accidentally sent thirty years into the past in a time-traveling car built by his eccentric scientist friend."),
    ("The Goonies", 1985, ("Adventure","Comedy","Family"), "Richard Donner", 7.7, 114, "A group of misfit kids uncover an old treasure map and set off on an adventure to save their neighborhood from foreclosure."),

    ("City of God", 2002, ("Crime","Drama"), "Fernando Meirelles, Katia Lund", 8.6, 130, "Two boys growing up in a violent Rio de Janeiro favela take vastly different paths, one into photography, the other into crime."),
    ("Life Is Beautiful", 1997, ("Comedy","Drama","Romance"), "Roberto Benigni", 8.6, 116, "A father uses humor and imagination to shield his young son from the horrors of a Nazi concentration camp."),
    ("Cinema Paradiso", 1988, ("Drama","Romance"), "Giuseppe Tornatore", 8.5, 155, "A filmmaker recalls his childhood friendship with the projectionist at his small village's movie theater."),
    ("Oldboy", 2003, ("Action","Drama","Mystery"), "Park Chan-wook", 8.4, 120, "A man seeks vengeance after being inexplicably imprisoned for fifteen years, then suddenly released without explanation."),
    ("Amores Perros", 2000, ("Drama","Thriller"), "Alejandro G. Inarritu", 8.1, 154, "Three interconnected stories in Mexico City collide around a single devastating car crash."),
    ("The Lives of Others", 2006, ("Drama","Thriller"), "Florian Henckel von Donnersmarck", 8.4, 137, "An East German secret police agent becomes increasingly absorbed in the lives of the artists he's surveilling."),
    ("A Separation", 2011, ("Drama",), "Asghar Farhadi", 8.3, 123, "A couple's divorce proceedings become entangled with a caregiving dispute that spirals into a complex moral and legal battle."),
    ("Roma", 2018, ("Drama",), "Alfonso Cuaron", 7.7, 135, "A live-in housekeeper for a middle-class family in 1970s Mexico City navigates upheaval both personal and political."),
    ("The Handmaiden", 2016, ("Drama","Romance","Thriller"), "Park Chan-wook", 8.1, 145, "A con man's elaborate plot to swindle an heiress is complicated by an unexpected and dangerous attraction."),

    ("Lost in Translation", 2003, ("Drama","Comedy","Romance"), "Sofia Coppola", 7.7, 102, "A fading movie star and a neglected young wife form an unexpected bond during a sleepless stay in Tokyo."),
    ("Juno", 2007, ("Comedy","Drama"), "Jason Reitman", 7.4, 96, "A sharp-witted teenager navigates an unplanned pregnancy with humor, resilience, and the support of an unlikely community."),
    ("The Perks of Being a Wallflower", 2012, ("Drama","Romance"), "Stephen Chbosky", 8.0, 103, "An introverted freshman finds his place in the world with the help of two eccentric seniors who welcome him into their circle."),
    ("Eighth Grade", 2018, ("Comedy","Drama"), "Bo Burnham", 7.4, 94, "A painfully shy teenager tries to survive the final week of middle school while grappling with anxiety and the pressures of social media."),
    ("Little Women", 2019, ("Drama","Romance"), "Greta Gerwig", 7.8, 135, "Four sisters navigate love, ambition, and independence in the years following the Civil War."),
    ("Lady Bird", 2017, ("Comedy","Drama"), "Greta Gerwig", 7.4, 94, "A strong-willed high school senior navigates a turbulent relationship with her mother during her final year in Sacramento."),
    ("The Farewell", 2019, ("Comedy","Drama"), "Lulu Wang", 7.5, 100, "A Chinese-American woman returns home to find her entire family hiding her grandmother's terminal diagnosis from her."),
    ("Call Me by Your Name", 2017, ("Drama","Romance"), "Luca Guadagnino", 7.8, 132, "A seventeen-year-old spends a transformative summer falling in love with his father's charismatic research assistant in Italy."),
    ("Brooklyn", 2015, ("Drama","Romance"), "John Crowley", 7.5, 111, "A young Irish immigrant builds a new life in 1950s New York, only to be torn between two countries and two loves."),
    ("The King's Speech", 2010, ("Drama","Biography","History"), "Tom Hooper", 8.0, 118, "A reluctant king struggling with a debilitating stutter works with an unconventional speech therapist to find his voice."),

    ("Inglourious Basterds", 2009, ("War","Drama","Thriller"), "Quentin Tarantino", 8.3, 153, "A team of Jewish-American soldiers and a vengeful cinema owner both plot to bring down the Nazi high command from opposite directions."),
    ("V for Vendetta", 2005, ("Action","Drama","Thriller"), "James McTeigue", 8.1, 132, "A masked vigilante wages a one-man war against a totalitarian government in a dystopian future Britain."),
    ("Kingsman: The Secret Service", 2014, ("Action","Adventure","Comedy"), "Matthew Vaughn", 7.7, 129, "A veteran spy recruits a street-smart young man into an elite, ultra-secretive independent intelligence agency."),
    ("The Equalizer", 2014, ("Action","Crime","Thriller"), "Antoine Fuqua", 7.2, 132, "A former black-ops operative comes out of quiet retirement to protect a young woman from a brutal crime syndicate."),
    ("Sicario", 2015, ("Action","Crime","Drama"), "Denis Villeneuve", 7.6, 121, "An idealistic FBI agent is drawn into the murky underworld of the US-Mexico drug war by a task force operating outside the law."),
    ("Extraction", 2020, ("Action","Thriller"), "Sam Hargrave", 6.8, 116, "A black-market mercenary is hired to rescue a kidnapped crime lord's son from a rival gang."),
    ("The Man from U.N.C.L.E.", 2015, ("Action","Adventure","Comedy"), "Guy Ritchie", 7.3, 116, "A CIA agent and a KGB operative are forced to put aside their rivalry to stop a criminal organization from building a nuclear weapon."),
    ("Snatch", 2000, ("Crime","Comedy"), "Guy Ritchie", 8.2, 104, "A stolen diamond sets off a chaotic chain of collisions between boxing promoters, gangsters, and a small-time jeweler."),
    ("Lock, Stock and Two Smoking Barrels", 1998, ("Crime","Comedy"), "Guy Ritchie", 8.1, 107, "Four friends who owe a massive debt to a crime boss scheme to rob their neighboring drug dealers to pay it off."),
    ("Collateral", 2004, ("Action","Crime","Drama"), "Michael Mann", 7.5, 120, "A cab driver's night takes a dangerous turn when his passenger turns out to be a contract killer working through a list of targets."),

    ("Spider-Man: Across the Spider-Verse", 2023, ("Animation","Action","Adventure"), "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson", 8.6, 140, "A young hero travels across the multiverse, only to clash with a team of Spider-People over how to handle a looming threat."),
    ("Kung Fu Panda", 2008, ("Animation","Action","Comedy"), "Mark Osborne, John Stevenson", 7.6, 92, "An overweight, clumsy panda is improbably chosen to fulfill an ancient prophecy as a legendary kung fu warrior."),
    ("Big Hero 6", 2014, ("Animation","Action","Adventure"), "Don Hall, Chris Williams", 7.8, 102, "A young robotics prodigy and his inflatable healthcare robot form a superhero team to catch a masked villain."),
    ("Moana", 2016, ("Animation","Adventure","Family"), "Ron Clements, John Musker", 7.6, 107, "A chief's daughter sets sail across the ocean to save her island, teaming up with a legendary but faded demigod."),
    ("Frozen", 2013, ("Animation","Adventure","Family"), "Chris Buck, Jennifer Lee", 7.4, 102, "A princess sets off to find her estranged sister, whose icy powers have accidentally trapped their kingdom in eternal winter."),
    ("The Nightmare Before Christmas", 1993, ("Animation","Fantasy","Family"), "Henry Selick", 7.9, 76, "The king of Halloween Town stumbles upon Christmas Town and decides to take over the holiday, with chaotic results."),
    ("Fantastic Mr. Fox", 2009, ("Animation","Adventure","Comedy"), "Wes Anderson", 7.9, 87, "A charming but reckless fox's return to poultry thievery puts his family and an entire community of animals at risk."),
    ("Kubo and the Two Strings", 2016, ("Animation","Adventure","Fantasy"), "Travis Knight", 7.6, 101, "A young boy with magical storytelling powers embarks on a quest to find a suit of armor to defeat vengeful spirits from his past."),
    ("Toy Story 3", 2010, ("Animation","Adventure","Comedy"), "Lee Unkrich", 8.3, 103, "As their owner leaves for college, a group of beloved toys is accidentally donated to a daycare with a tyrannical ruling bear."),
    ("Song of the Sea", 2014, ("Animation","Adventure","Family"), "Tomm Moore", 7.9, 93, "A young boy and his mute sister discover she is a mythical selkie destined to free the fairy folk trapped by an old curse."),

    ("Being John Malkovich", 1999, ("Comedy","Drama","Fantasy"), "Spike Jonze", 7.7, 113, "A puppeteer discovers a portal that leads directly into the mind of a famous actor, with strange and hilarious consequences."),
    ("Adaptation", 2002, ("Comedy","Drama"), "Spike Jonze", 7.7, 115, "A screenwriter struggles to adapt a challenging book while his twin brother effortlessly breaks into the same industry."),
    ("Trainspotting", 1996, ("Drama","Crime"), "Danny Boyle", 8.1, 94, "A group of heroin addicts in Edinburgh navigate friendship, addiction, and the fleeting pull of a better life."),
    ("Slumdog Millionaire", 2008, ("Drama","Romance"), "Danny Boyle", 8.0, 120, "A young man from the slums of Mumbai becomes a suspect after answering every question correctly on a game show."),
    ("Snowpiercer", 2013, ("Action","Sci-Fi","Thriller"), "Bong Joon-ho", 7.1, 126, "The last survivors of a frozen world live aboard a perpetually moving train divided by a brutal class system."),
    ("Okja", 2017, ("Adventure","Drama","Sci-Fi"), "Bong Joon-ho", 7.3, 120, "A young girl sets out to rescue her genetically engineered best friend from the corporation that wants to slaughter it."),
    ("Memories of Murder", 2003, ("Crime","Drama","Mystery"), "Bong Joon-ho", 8.1, 132, "Detectives in a small Korean town struggle to catch an elusive serial killer terrorizing the community."),
    ("Burning", 2018, ("Drama","Mystery","Thriller"), "Lee Chang-dong", 7.5, 148, "A young delivery worker's reunion with a childhood friend takes a dark turn when she introduces him to her wealthy, enigmatic companion."),

    ("Pirates of the Caribbean: The Curse of the Black Pearl", 2003, ("Action","Adventure","Fantasy"), "Gore Verbinski", 8.1, 143, "A blacksmith teams up with an eccentric pirate captain to rescue the governor's daughter from a crew of cursed buccaneers."),
    ("Monsters, Inc.", 2001, ("Animation","Adventure","Comedy"), "Pete Docter, David Silverman", 8.1, 92, "Two monster co-workers who scare children for a living discover a little girl has wandered into their world."),
    ("Bird Box", 2018, ("Horror","Sci-Fi","Thriller"), "Susanne Bier", 6.6, 124, "A woman and two children must navigate a dangerous river blindfolded to escape creatures that drive anyone who sees them to violence."),
    ("World War Z", 2013, ("Action","Horror","Sci-Fi"), "Marc Forster", 7.0, 116, "A former UN investigator races around the globe to find a way to stop a pandemic that is rapidly turning humanity into the undead."),
    ("I Am Legend", 2007, ("Drama","Horror","Sci-Fi"), "Francis Lawrence", 7.2, 101, "A scientist believes he may be the last uninfected human in a New York City overrun by the infected after a failed cure for cancer."),
    ("Contagion", 2011, ("Drama","Thriller"), "Steven Soderbergh", 6.6, 106, "Doctors, scientists, and government officials race to contain a rapidly spreading and deadly airborne virus."),
    ("The Martian", 2015, ("Adventure","Drama","Sci-Fi"), "Ridley Scott", 8.0, 144, "An astronaut is presumed dead and left behind on Mars, and must use his ingenuity to survive until a rescue mission can reach him."),
    ("Gravity", 2013, ("Drama","Sci-Fi","Thriller"), "Alfonso Cuaron", 7.7, 91, "Two astronauts are stranded in space after debris destroys their shuttle, forcing a desperate fight to get back to Earth."),
    ("Passengers", 2016, ("Adventure","Drama","Romance"), "Morten Tyldum", 7.0, 116, "Two passengers on a colony ship wake from suspended animation ninety years too early, with only each other for company."),
    ("Elysium", 2013, ("Action","Drama","Sci-Fi"), "Neill Blomkamp", 6.6, 109, "In a future where the wealthy live on a luxurious space station, a factory worker fights for a chance to access its life-saving technology."),

    ("Ready Player One", 2018, ("Action","Adventure","Sci-Fi"), "Steven Spielberg", 7.4, 140, "In a bleak future, a young man competes in a virtual reality contest to inherit the fortune and control of its late creator."),
    ("Tenet", 2020, ("Action","Sci-Fi","Thriller"), "Christopher Nolan", 7.3, 150, "A secret agent armed with the ability to manipulate the flow of time works to prevent a catastrophic assault on the present."),
    ("Annihilation", 2018, ("Sci-Fi","Horror","Mystery"), "Alex Garland", 6.8, 115, "A biologist joins an expedition into a mysterious, mutating zone where the laws of nature no longer seem to apply."),
    ("Coherence", 2013, ("Sci-Fi","Drama","Mystery"), "James Ward Byrkit", 7.2, 89, "A dinner party spirals into chaos when a passing comet causes strange, reality-bending events among the guests."),
    ("Primer", 2004, ("Sci-Fi","Drama","Mystery"), "Shane Carruth", 6.9, 77, "Two engineers accidentally build a time machine in their garage, and quickly lose control of the consequences."),
    ("Moon", 2009, ("Drama","Mystery","Sci-Fi"), "Duncan Jones", 7.8, 97, "A lone astronaut nearing the end of a solitary three-year contract on the moon begins to question everything about his mission."),
    ("Source Code", 2011, ("Action","Mystery","Sci-Fi"), "Duncan Jones", 7.5, 93, "A soldier repeatedly relives the final minutes of a train bombing in the body of another man, trying to identify the culprit."),
    ("Predestination", 2014, ("Sci-Fi","Mystery","Thriller"), "Michael Spierig, Peter Spierig", 7.5, 97, "A time-traveling agent takes on one final, deeply personal assignment to stop a bomber who has eluded him his entire career."),
    ("Chappie", 2015, ("Action","Sci-Fi","Thriller"), "Neill Blomkamp", 6.8, 120, "A stolen police robot is reprogrammed to think and feel for itself, drawing the attention of both criminals and the military."),
    ("Pacific Rim", 2013, ("Action","Adventure","Sci-Fi"), "Guillermo del Toro", 7.0, 132, "Giant robots piloted by paired humans are humanity's last defense against enormous monsters rising from the depths of the ocean."),

    ("The Shape of Water", 2017, ("Drama","Fantasy","Romance"), "Guillermo del Toro", 7.3, 123, "A mute cleaning woman at a secret government facility forms an unlikely bond with an amphibious creature held captive there."),
    ("Crimson Peak", 2015, ("Drama","Fantasy","Horror"), "Guillermo del Toro", 6.5, 119, "A young author moves into her new husband's crumbling ancestral mansion, where dark secrets and restless spirits await."),
    ("Hellboy", 2004, ("Action","Fantasy","Horror"), "Guillermo del Toro", 6.8, 122, "A demon raised from infancy by a secret government agency grows up to battle the forces of darkness he was destined to join."),
    ("Nightmare Alley", 2021, ("Drama","Thriller"), "Guillermo del Toro", 6.7, 150, "An ambitious carnival worker rises through the ranks of a traveling sideshow before a cunning psychiatrist proves his own match."),

    ("La Haine", 1995, ("Crime","Drama"), "Mathieu Kassovitz", 8.1, 98, "Three friends in a rough Paris suburb spend twenty-four tense hours in the aftermath of a riot sparked by police violence."),
    ("Y Tu Mama Tambien", 2001, ("Drama","Romance"), "Alfonso Cuaron", 7.6, 106, "Two teenage friends and an older woman set off on a spontaneous road trip that reshapes all three of their lives."),
    ("Central Station", 1998, ("Drama",), "Walter Salles", 7.9, 110, "A jaded former teacher reluctantly helps a young orphan boy search for the father he has never met across Brazil."),
    ("The Battle of Algiers", 1966, ("Drama","War","History"), "Gillo Pontecorvo", 8.1, 121, "A docudrama chronicles the escalating guerrilla conflict between revolutionaries and colonial forces in 1950s Algiers."),
    ("Seven Samurai", 1954, ("Action","Adventure","Drama"), "Akira Kurosawa", 8.6, 207, "A poor farming village hires seven masterless samurai to defend them from a band of marauding bandits."),
    ("Rashomon", 1950, ("Crime","Drama","Mystery"), "Akira Kurosawa", 8.2, 88, "Four witnesses give conflicting accounts of a samurai's murder and his wife's assault in the forest."),
    ("Ikiru", 1952, ("Drama",), "Akira Kurosawa", 8.3, 143, "A terminally ill bureaucrat searches for meaning in his remaining days after a lifetime of quiet routine."),
    ("Ponyo", 2008, ("Animation","Adventure","Family"), "Hayao Miyazaki", 7.7, 101, "A young goldfish princess longs to become human after being rescued by a kind five-year-old boy."),
    ("The Wind Rises", 2013, ("Animation","Biography","Drama"), "Hayao Miyazaki", 7.8, 126, "An aircraft designer's lifelong dream of flight collides with the looming shadow of war in 1930s Japan."),
    ("Grave of the Fireflies", 1988, ("Animation","Drama","War"), "Isao Takahata", 8.5, 89, "A teenage boy and his younger sister struggle to survive in the devastating final months of World War II Japan."),

    ("Synecdoche, New York", 2008, ("Drama",), "Charlie Kaufman", 7.5, 124, "A theater director embarks on an increasingly vast and personal production that begins to blur the line between his life and his art."),
    ("I'm Thinking of Ending Things", 2020, ("Drama","Mystery"), "Charlie Kaufman", 6.5, 134, "A woman having doubts about her new boyfriend embarks on a road trip to meet his parents at their remote farm."),
    ("Melancholia", 2011, ("Drama","Sci-Fi"), "Lars von Trier", 7.1, 136, "Two sisters' already fraught relationship is tested to the breaking point as a rogue planet hurtles toward a collision with Earth."),
    ("Dogville", 2003, ("Crime","Drama","Thriller"), "Lars von Trier", 8.0, 178, "A woman on the run finds refuge in a small mountain town, whose residents slowly begin to take advantage of her gratitude."),
    ("The Lighthouse", 2019, ("Drama","Fantasy","Horror"), "Robert Eggers", 7.4, 109, "Two lighthouse keepers' isolation on a remote New England island gives way to paranoia, rivalry, and madness."),
    ("The Northman", 2022, ("Action","Adventure","Drama"), "Robert Eggers", 7.0, 137, "A Viking prince sets out on a brutal quest for revenge after his father is murdered and his kingdom stolen."),

    ("Drive", 2011, ("Crime","Drama","Thriller"), "Nicolas Winding Refn", 7.8, 100, "A Hollywood stunt driver who moonlights as a getaway driver gets pulled into a violent robbery gone wrong to protect his neighbor."),
    ("Only God Forgives", 2013, ("Crime","Drama","Thriller"), "Nicolas Winding Refn", 5.6, 90, "An expatriate drug smuggler in Bangkok is pushed by his ruthless mother to avenge his brother's death."),
    ("The Florida Project", 2017, ("Drama",), "Sean Baker", 7.6, 111, "A precocious six-year-old and her friends spend a vibrant summer in the shadow of a Florida resort, unaware of her mother's desperate struggles."),
    ("Nomadland", 2020, ("Drama",), "Chloe Zhao", 7.3, 108, "A woman in her sixties embraces a nomadic life on the road after losing everything in the economic collapse of her Nevada town."),
    ("The Rider", 2017, ("Drama",), "Chloe Zhao", 7.4, 104, "A young rodeo star must reckon with his identity and purpose after a near-fatal injury ends his riding career."),

    ("Boyhood", 2014, ("Drama",), "Richard Linklater", 7.9, 165, "A boy's childhood and adolescence are captured on film over twelve real years, alongside his divorced parents and sister."),
    ("Before Sunset", 2004, ("Drama","Romance"), "Richard Linklater", 8.1, 80, "Two former lovers reunite for one afternoon in Paris nearly a decade after their first unforgettable encounter."),
    ("Before Midnight", 2013, ("Drama","Romance"), "Richard Linklater", 7.9, 109, "Nearly two decades after they first met, a couple confronts the everyday tensions and doubts of a long relationship on a Greek vacation."),
    ("Dazed and Confused", 1993, ("Comedy","Drama"), "Richard Linklater", 7.6, 102, "A sprawling ensemble of high schoolers navigates the last day of school and a wild night of parties in 1976 Texas."),
    ("School of Rock", 2003, ("Comedy","Family","Music"), "Richard Linklater", 7.1, 109, "A failed rock musician poses as a substitute teacher and secretly turns his class of gifted kids into a band."),

    ("Punch-Drunk Love", 2002, ("Comedy","Drama","Romance"), "Paul Thomas Anderson", 7.3, 95, "A socially awkward small business owner's chaotic life takes an unexpected turn when he falls for his sister's friend."),
    ("Magnolia", 1999, ("Drama",), "Paul Thomas Anderson", 8.0, 188, "A mosaic of interconnected characters across the San Fernando Valley confront chance, coincidence, and forgiveness over one strange day."),
    ("Boogie Nights", 1997, ("Drama",), "Paul Thomas Anderson", 7.9, 155, "A young dishwasher's rise to stardom in the 1970s adult film industry gives way to excess and unraveling in the decade that follows."),
    ("Licorice Pizza", 2021, ("Comedy","Drama","Romance"), "Paul Thomas Anderson", 7.2, 133, "A teenage actor and a directionless twenty-something forge an unlikely bond across a sun-drenched San Fernando Valley coming of age."),

    ("The Dark Knight Rises", 2012, ("Action","Drama","Thriller"), "Christopher Nolan", 8.4, 164, "Eight years after his disappearance, a masked mercenary threatens to bring Gotham to its knees, forcing a vigilante's return."),
    ("Batman Begins", 2005, ("Action","Crime","Drama"), "Christopher Nolan", 8.2, 140, "A billionaire orphan is trained by a secret league of assassins before returning to Gotham to wage a one-man war on crime."),
    ("Insomnia", 2002, ("Crime","Drama","Mystery"), "Christopher Nolan", 7.2, 118, "A detective investigating a murder in a small Alaskan town where the sun never sets becomes consumed by guilt after a fatal mistake."),
    ("Oppenheimer", 2023, ("Biography","Drama","History"), "Christopher Nolan", 8.3, 180, "The story of the physicist who led the effort to build the first atomic bomb, and the moral reckoning that followed."),

    ("Babylon", 2022, ("Comedy","Drama","History"), "Damien Chazelle", 7.2, 189, "An ensemble of dreamers and schemers rides the wild, decadent rise and ruin of Hollywood's transition from silent films to sound."),
    ("First Man", 2018, ("Biography","Drama","History"), "Damien Chazelle", 7.3, 141, "The story of the dangerous missions and personal sacrifices that led to Neil Armstrong becoming the first man to walk on the moon."),

    ("The Trial of the Chicago 7", 2020, ("Drama","History","Thriller"), "Aaron Sorkin", 7.8, 129, "Seven activists face a chaotic and politically charged trial after violent protests erupt at the 1968 Democratic National Convention."),
    ("Molly's Game", 2017, ("Biography","Crime","Drama"), "Aaron Sorkin", 7.4, 140, "A former Olympic-class skier builds and runs the world's most exclusive high-stakes underground poker game."),
    ("A Few Good Men", 1992, ("Drama","Thriller"), "Rob Reiner", 7.7, 138, "Two military lawyers defend Marines accused of murder, uncovering a chain of command that may have ordered the killing."),
    ("Stand By Me", 1986, ("Adventure","Drama"), "Rob Reiner", 8.1, 89, "Four boys set off on a journey along the railroad tracks to find the body of a missing local teenager."),
    ("Misery", 1990, ("Drama","Thriller","Horror"), "Rob Reiner", 7.8, 107, "An injured novelist is held captive by his obsessive number one fan after a car crash strands him in a remote mountain cabin."),
    ("This Is Spinal Tap", 1984, ("Comedy","Music"), "Rob Reiner", 8.2, 82, "A fictional rock band's chaotic American tour is chronicled by a documentary crew, capturing every disastrous mishap along the way."),
]

# ---- Validation ----
titles_seen = set()
for (title, year, genres, director, rating, runtime, desc) in MOVIES:
    if title in titles_seen:
        raise ValueError(f"Duplicate title: {title}")
    titles_seen.add(title)
    for g in genres:
        if g not in ALLOWED_GENRES:
            raise ValueError(f"Unrecognized genre '{g}' on '{title}'")
    if not (1900 < year < 2027):
        raise ValueError(f"Suspicious year on '{title}': {year}")
    if not (0 <= rating <= 10):
        raise ValueError(f"Suspicious rating on '{title}': {rating}")
    if not (30 < runtime < 250):
        raise ValueError(f"Suspicious runtime on '{title}': {runtime}")

# ---- Build JSON ----
result = []
for i, (title, year, genres, director, rating, runtime, desc) in enumerate(MOVIES, start=1):
    result.append({
        "id": i,
        "title": title,
        "year": year,
        "genres": list(genres),
        "director": director,
        "rating": rating,
        "runtime": runtime,
        "description": desc,
    })

with open("/home/claude/movie-recommendation-app/backend/data/movies.json", "w") as f:
    json.dump(result, f, indent=2)

print(f"Wrote {len(result)} movies.")
genre_counts = {}
for m in result:
    for g in m["genres"]:
        genre_counts[g] = genre_counts.get(g, 0) + 1
for g, c in sorted(genre_counts.items()):
    print(f"  {g}: {c}")
